# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=250)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('plan', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plancreator', to='loginregistration.User')),
                ('userplan', models.ManyToManyField(related_name='userlink', to='loginregistration.User')),
            ],
        ),
    ]
